debug = false
disable_crowdin = false
check_for_updates = true

[[key_bindings]]
keys = []
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
keys = []
name = "key.plasmovoice.general.action"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 88
type = "KEYSYM"

[servers.2cb6df55-69b8-4d0b-9415-392d98fc3dfc.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = false

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
use_javax_input = false
microphone_volume = 2.0
noise_suppression = false
volume = 2.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_185ab151-0f3c-43c6-a59e-30951ab67954]
volume = 1.0
[voice.volumes.source_f208686f-f32e-4e80-8b9e-585ae574fb7a]
volume = 1.0
[voice.volumes.proximity]
volume = 2.0
[voice.volumes.source_b6a683cd-32da-4704-a8e5-6c88a21cad56]
volume = 1.0
[voice.volumes.source_35b3c8f8-c6d4-418e-b160-180a351f445a]
volume = 1.0
[voice.volumes.source_cd56fb49-7116-484f-bd4e-4b0f1724b893]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
